"""empty message

Revision ID: 513706f60c2e
Revises: 1b93720d155e
Create Date: 2024-03-15 00:24:59.554442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513706f60c2e'
down_revision = '1b93720d155e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('reservation_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_unique_constraint('reservation_name_key', ['name'])

    # ### end Alembic commands ###
